name: Pipeline that executes jobs against QA.
on:
  push:
    branches:
      - develop
jobs:
  send_to_s3: 
    uses: diegodurli/gha/.github/workflows/upload_to_s3.yml@main
    with:
      aws_region: us-east-1
      assumed_role: ${{ secrets.AWS_ASSUMED_ROLE }}
      destination_bucket: ddconfigtest
      file_path: ./config/file.json