name: Pipeline that executes jobs against Prod.
on:
  push:
    branches:
      - main
jobs:
  send_to_s3: 
    uses: diegodurli/gha/.github/workflows/upload_to_s3.yml@main
    secrets:
      assumed_role: ${{ secrets.AWS_ASSUMED_ROLE_PROD1 }}
      destination_bucket: ${{ secrets.AWS_DESTINATION_BUCKET }}
    with:
      aws_region: us-east-1
      file_path: ./config/file.json
