name: Validate the File against a defined schema.
on: [pull_request]
jobs:
  schema_validation: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate a config file against a schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: 'config/file.json'
          schema: 'schema/config.json'