name: Upload to S3 using a assumed-role
on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      assumed_role:
        required: true
        type: string
      destination_bucket:
        required: true
        type: string
      file_path:
        required: true
        type: string
jobs:
  send_to_s3: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.assumed_role }}
          aws-region: ${{ inputs.aws_region }}

      - name: Upload to S3
        run: |
          aws s3 sync ${{ inputs.file_path }} s3://${{ inputs.destination_bucket }}